version: "3.7"
services:
  db:
    image: mjm2312/db:latest 
    environment:
      POSTGRES_USER: ${PG_USER}
      #POSTGRES_PASSWORD: ${PG_PASSWORD}
      #PG_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"
  server: 
    environment: 
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT} 
    image: mjm2312/api:latest
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"