version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      #POSTRES_PASSWORD: postgres is not working without POSTGRES_HOST_AUTH_METHOD
    
    volumes:
      - ./db/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
      - ./db/schema.sql:/schema.sql
      - ./db/answers_photos_transformed.csv:/answers_photos_transformed.csv
      - ./pgdata:/var/lib/postgresql/data


    ports:
      - "5432:5432"
  server: 
    #image: mjm2312/questions-and-answers nodemon may cause error w kubernetes, this image uses nodemon
    image: mjm2312/questions-and-answers-cmd-node
    depends_on:
      - db
   # volumes: # suppressing this because getting error with kubernetes.
   #   - .:/src
    ports:
      - "3001:3001"