kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-initdb-pv-claim-march-04
  labels:
    app: db
  # issue mounting to var/lib/psotgres/data https://github.com/docker-library/postgres/issues/116
  #annotations:
    #volume.beta.kubernetes.io/mount-options: "dir_mode=0777,file_mode=0777,uid=1000,gid=1000"

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 
      #1Mi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-initdb-pv-volume-march-04
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
    #1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/mattmartin/HackReactor/questions-and-answers/db-in-minikube"
    #path: "data/Users/mattmartin/HackReactor/questions-and-answers/"


