apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - image: mjm2312/0420-api-5
        imagePullPolicy: ""
        name: server
        ports:
        - containerPort: 3001
        resources: {}
        #test if this will link to the db
        # envFrom:
        # - configMapRef:
        #     name: server-side-configs
        #end test
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
